### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by joemerlino** [sevazhidkov/leonard#1]
On first run it asks for: 

    Enter message: 
    Enter a comma-separated attachments(<type>_<path>):

What I should enter in both lines? 
Thanks!

**Comment by sevazhidkov** [comment]
Hi! This is console adapter: you can use it for testing your plugins. If you want to change adapter, just run bot with adapter name after bot language.
For example,
```
python start.py en telegram
```

First of December will be a new version of the bot with new powerful features based on https://github.com/sevazhidkov/sheldon

**Comment by joemerlino** [comment]
Awesome! I'll look forward to try it out on December 1st :) If you can improve that README.md would be great! 
Thanks
